import { ElectricBusModel } from '@/types';

export const BUS_MODELS: ElectricBusModel[] = [
  {
    id: 'byd-k9',
    modelName: 'K9',
    manufacturer: 'BYD',
    rangeKm: 250,
    batteryCapacityKwh: 324,
    chargingTimeHours: 4,
    energyConsumptionKwhPerKm: 1.3,
    passengerCapacity: 80,
    lengthMeters: 12,
    widthMeters: 2.55,
    heightMeters: 3.36,
    weightKg: 18000,
    unitCostUsd: 550000,
    maintenanceCostPerKm: 0.15,
    warrantyYears: 12,
    imageUrl: '/images/buses/byd-k9.jpg',
  },
  {
    id: 'byd-k7',
    modelName: 'K7',
    manufacturer: 'BYD',
    rangeKm: 200,
    batteryCapacityKwh: 215,
    chargingTimeHours: 3.5,
    energyConsumptionKwhPerKm: 1.1,
    passengerCapacity: 60,
    lengthMeters: 10.5,
    widthMeters: 2.5,
    heightMeters: 3.2,
    weightKg: 14500,
    unitCostUsd: 420000,
    maintenanceCostPerKm: 0.12,
    warrantyYears: 10,
    imageUrl: '/images/buses/byd-k7.jpg',
  },
  {
    id: 'yutong-e12',
    modelName: 'E12',
    manufacturer: 'Yutong',
    rangeKm: 300,
    batteryCapacityKwh: 422,
    chargingTimeHours: 4.5,
    energyConsumptionKwhPerKm: 1.4,
    passengerCapacity: 90,
    lengthMeters: 12,
    widthMeters: 2.55,
    heightMeters: 3.4,
    weightKg: 19000,
    unitCostUsd: 480000,
    maintenanceCostPerKm: 0.14,
    warrantyYears: 8,
    imageUrl: '/images/buses/yutong-e12.jpg',
  },
  {
    id: 'volvo-7900e',
    modelName: '7900 Electric',
    manufacturer: 'Volvo',
    rangeKm: 220,
    batteryCapacityKwh: 396,
    chargingTimeHours: 6,
    energyConsumptionKwhPerKm: 1.8,
    passengerCapacity: 95,
    lengthMeters: 12,
    widthMeters: 2.55,
    heightMeters: 3.3,
    weightKg: 19500,
    unitCostUsd: 650000,
    maintenanceCostPerKm: 0.18,
    warrantyYears: 10,
    imageUrl: '/images/buses/volvo-7900e.jpg',
  },
  {
    id: 'proterra-zx5',
    modelName: 'ZX5',
    manufacturer: 'Proterra',
    rangeKm: 400,
    batteryCapacityKwh: 660,
    chargingTimeHours: 5,
    energyConsumptionKwhPerKm: 1.65,
    passengerCapacity: 77,
    lengthMeters: 12.2,
    widthMeters: 2.6,
    heightMeters: 3.35,
    weightKg: 17800,
    unitCostUsd: 750000,
    maintenanceCostPerKm: 0.16,
    warrantyYears: 12,
    imageUrl: '/images/buses/proterra-zx5.jpg',
  },
  {
    id: 'new-flyer-xe40',
    modelName: 'Xcelsior XE40',
    manufacturer: 'New Flyer',
    rangeKm: 280,
    batteryCapacityKwh: 466,
    chargingTimeHours: 4,
    energyConsumptionKwhPerKm: 1.66,
    passengerCapacity: 70,
    lengthMeters: 12.2,
    widthMeters: 2.6,
    heightMeters: 3.2,
    weightKg: 18500,
    unitCostUsd: 800000,
    maintenanceCostPerKm: 0.17,
    warrantyYears: 12,
    imageUrl: '/images/buses/new-flyer-xe40.jpg',
  },
];

export const getBusModel = (id: string): ElectricBusModel | undefined => {
  return BUS_MODELS.find((bus) => bus.id === id);
};
